import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { API_BASE_URL, returnsAPI } from '../../services/api';
import { formatCurrency } from '../../utils/format';

const STATUS:Record<string,string>={CHO_DUYET:'Chờ duyệt',DA_DUYET:'Đã duyệt',TU_CHOI:'Từ chối',CHO_KHACH_GUI_HANG:'Chờ khách gửi hàng',CHO_LAY_HANG_HOAN:'Chờ lấy hàng hoàn',DA_LAY_HANG_HOAN:'Đã lấy hàng',DANG_HOAN_VE:'Đang hoàn về',DA_NHAN_HANG_HOAN:'Chờ kiểm tra',DANG_KIEM_TRA:'Đang kiểm tra',CHAP_NHAN_HOAN:'Chờ xử lý kho',TU_CHOI_SAU_KIEM_TRA:'Từ chối sau kiểm tra',CHO_HOAN_TIEN:'Chờ hoàn tiền',DANG_HOAN_TIEN:'Đang hoàn tiền',DA_HOAN_TIEN:'Đã hoàn tiền',DA_DOI_HANG:'Đã đổi hàng',HOAN_TAT:'Hoàn tất',DA_HUY:'Đã hủy'};
const image=(url?:string)=>url?url.startsWith('http')?url:`${API_BASE_URL.replace(/\/api\/?$/,'')}${url.startsWith('/')?url:`/${url}`}`:'';

export default function ChiTietHoanTra(){
  const {id}=useParams();const navigate=useNavigate();const [data,setData]=useState<any>();const [error,setError]=useState('');
  const load=async()=>{try{setError('');const r=await returnsAPI.getById(Number(id));setData(r.data.data)}catch(e:any){setError(e.response?.data?.message||e.message||'Không thể tải yêu cầu')}};
  useEffect(()=>{void load()},[id]);
  return <div className="min-h-screen bg-slate-50 p-6"><button onClick={()=>navigate('/returns')} className="mb-4 text-sm text-pink-600">← Quay lại yêu cầu hoàn trả</button>{error?<div className="rounded-xl bg-red-50 p-6 text-red-700">{error}<button onClick={()=>void load()} className="ml-3 underline">Thử lại</button></div>:!data?<div className="p-12 text-center text-slate-400">Đang tải…</div>:<div className="mx-auto max-w-4xl space-y-4"><header className="rounded-xl bg-white p-5 shadow-sm"><h1 className="text-xl font-bold">{data.MaYeuCau} · {STATUS[data.TrangThai]||data.TrangThai}</h1><p className="mt-2 text-sm text-slate-500">Đơn {data.MaHoaDonHienThi} · {data.TenKhachHang} · {data.SoDienThoai}</p></header><section className="rounded-xl bg-white p-5 shadow-sm"><h2 className="mb-3 font-bold">Sản phẩm và tính tiền hoàn</h2>{data.chiTiet?.map((item:any)=><div key={item.Id} className="flex items-center gap-3 border-b py-3"><img src={image(item.HinhAnh)} onError={e=>{e.currentTarget.style.visibility='hidden'}} className="h-12 w-12 rounded object-cover"/><div className="flex-1"><b>{item.TenSanPham}</b><div className="text-xs text-slate-500">Trả {item.SoLuongTra} / {item.SoLuongMua} · giá lúc mua {formatCurrency(item.DonGiaSnapshot)}</div></div><b>{formatCurrency(item.SoTienDuKien)}</b></div>)}<p className="mt-4 text-right text-lg font-bold text-pink-600">Dự kiến: {formatCurrency(data.SoTienDuKien)}</p><p className="text-right text-sm text-slate-500">Giảm giá phân bổ {formatCurrency(data.GiamGiaPhanBo)} · phí khách chịu {formatCurrency(data.PhiHoanKhachChiu)}</p></section><section className="rounded-xl bg-white p-5 shadow-sm"><h2 className="mb-3 font-bold">Timeline</h2>{data.timeline?.map((step:any)=><div key={step.Id} className="border-l-2 border-pink-200 py-2 pl-4"><b>{STATUS[step.TrangThaiMoi]||step.TrangThaiMoi}</b><p className="text-xs text-slate-500">{new Date(step.NgayTao).toLocaleString('vi-VN')} · {step.TenNguoiThaoTac} · {step.GhiChu}</p></div>)}</section></div>}</div>;
}
