import { useCallback, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import api from '../../services/api';
import { formatCurrency } from '../../utils/format';

type Tab='items'|'lots'|'expiry'|'moves';
type Dashboard={stats:{tongTon:number;giaTriTonKho:number;sapHet:number;sapHetHan:number;phieuChoXacNhan:number};alerts:any[];chart:any[]};
type Option={MaSanPham:number;TenSanPham:string;MaSKU?:string};
const today=()=>new Date().toISOString().slice(0,10);
const fmt=(v?:string)=>v?new Date(v).toLocaleDateString('vi-VN'):'—';
const emptyReceipt=()=>({MaNCC:'',NgayNhap:today(),GhiChu:'',items:[{MaSanPham:'',MaLoCode:'',NgaySanXuat:'',HanSuDung:'',SoLuong:1,GiaNhap:0,ViTri:''}]});
const message=(e:any)=>{if(!e.response)return 'Không thể kết nối máy chủ Backend tại port 3000.';const s=e.response.status;if(s===401)return 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.';if(s===403)return 'Tài khoản không có quyền quản lý kho.';if(s===404)return 'Không tìm thấy API kho. Hãy khởi động lại Backend.';if(s>=500)return `Lỗi Backend/database: ${e.response.data?.message||'Không xác định'}`;return e.response.data?.message||'Không thể xử lý yêu cầu.'};
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-auto rounded-2xl bg-white shadow-xl"><div className="sticky top-0 flex items-center justify-between border-b bg-white p-5"><h2 className="text-xl font-bold">{title}</h2><button onClick={onClose}>✕</button></div><div className="p-5">{children}</div></div></div>}

export default function KhoHang(){
 const [searchParams]=useSearchParams();
 const linkedProductId=Number(searchParams.get('productId')||0);
 const user=useMemo(()=>JSON.parse(localStorage.getItem('user')||'{}'),[]),isAdmin=user.VaiTro==='Admin';
 const [dashboard,setDashboard]=useState<Dashboard|null>(null),[rows,setRows]=useState<any[]>([]),[tab,setTab]=useState<Tab>('items'),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[pages,setPages]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [categories,setCategories]=useState<any[]>([]),[products,setProducts]=useState<Option[]>([]),[suppliers,setSuppliers]=useState<any[]>([]),[allLots,setAllLots]=useState<any[]>([]),[receipts,setReceipts]=useState<any[]>([]),[counts,setCounts]=useState<any[]>([]);
 const [receiptOpen,setReceiptOpen]=useState(false),[receipt,setReceipt]=useState(emptyReceipt),[countOpen,setCountOpen]=useState(false),[countForm,setCountForm]=useState({MaLo:'',TonThucTe:0,LyDo:'',GhiChu:''}),[detail,setDetail]=useState<any>(null);
 const [replenishmentRequests,setReplenishmentRequests]=useState<any[]>([]),[requestError,setRequestError]=useState('');

 const loadDashboard=useCallback(async()=>{const r=await api.get('/khohang/dashboard');setDashboard(r.data.data)},[]);
 const loadRows=useCallback(async()=>{const endpoint=tab==='items'?'/khohang/items':tab==='moves'?'/khohang/transactions':'/khohang/lots';const params:any={page,limit:10,search,category};if(tab==='expiry')params.expiry='soon';if(tab==='items'){params.status=status;if(linkedProductId)params.productId=linkedProductId}const r=await api.get(endpoint,{params});setRows(r.data.data||[]);setPages(r.data.pagination?.totalPages||1)},[tab,page,search,category,status,linkedProductId]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{await Promise.all([loadDashboard(),loadRows()]);const c=await api.get('/danhmuc');setCategories(c.data.data||[])}catch(e){setError(message(e))}finally{setLoading(false)}},[loadDashboard,loadRows]);
 useEffect(()=>{load()},[load]);
 const loadOptions=async()=>{try{const [p,s,l,r,c]=await Promise.all([api.get('/sanpham',{params:{limit:100}}),api.get('/khohang/suppliers'),api.get('/khohang/lots',{params:{limit:100}}),api.get('/khohang/receipts'),api.get('/khohang/counts')]);setProducts(p.data.data||[]);setSuppliers(s.data.data||[]);setAllLots(l.data.data||[]);setReceipts(r.data.data||[]);setCounts(c.data.data||[])}catch(e){setError(message(e))}};
 const openReceipt=async()=>{await loadOptions();setReceipt(emptyReceipt());setReceiptOpen(true)};
 const openCount=async()=>{await loadOptions();setCountForm({MaLo:'',TonThucTe:0,LyDo:'',GhiChu:''});setCountOpen(true)};
 const saveReceipt=async(send=false)=>{setError('');try{const r=await api.post('/khohang/receipts',receipt);if(send)await api.post(`/khohang/receipts/${r.data.data.MaPhieuNhap}/submit`);setNotice(send?'Đã gửi phiếu nhập chờ Admin xác nhận.':'Đã lưu phiếu nhập nháp; tồn kho chưa thay đổi.');await loadOptions();await load();if(!send)setReceiptOpen(false)}catch(e){setError(message(e))}};
 const confirmReceipt=async(id:number)=>{try{await api.post(`/khohang/receipts/${id}/confirm`);setNotice('Đã xác nhận phiếu nhập và cập nhật tồn kho đúng một lần.');await loadOptions();await load()}catch(e){setError(message(e))}};
 const selectedLot=allLots.find(x=>String(x.MaLo)===String(countForm.MaLo));
 const saveCount=async(send=false)=>{try{const r=await api.post('/khohang/counts',{LyDo:countForm.LyDo,GhiChu:countForm.GhiChu,items:[{MaLo:Number(countForm.MaLo),TonThucTe:Number(countForm.TonThucTe)}]});if(send)await api.post(`/khohang/counts/${r.data.data.MaPhieuKiemKe}/submit`);setNotice(send?'Đã gửi phiếu kiểm kê chờ xác nhận.':'Đã lưu kiểm kê nháp; tồn kho chưa thay đổi.');await loadOptions();if(!send)setCountOpen(false)}catch(e){setError(message(e))}};
 const confirmCount=async(id:number)=>{try{await api.post(`/khohang/counts/${id}/confirm`);setNotice('Đã xác nhận chênh lệch kiểm kê.');await loadOptions();await load()}catch(e){setError(message(e))}};
 const showDetail=async(id:number)=>{try{const r=await api.get(`/khohang/items/${id}`);setDetail(r.data.data)}catch(e){setError(message(e))}};
 const loadReplenishmentRequests=useCallback(async()=>{if(!isAdmin)return;setRequestError('');try{const r=await api.get('/khohang/replenishment-requests',{params:{page:1,limit:100,status:'CHO_DUYET'}});setReplenishmentRequests(r.data.data||[])}catch(e){setRequestError(message(e))}},[isAdmin]);
 useEffect(()=>{if(isAdmin)void loadReplenishmentRequests()},[isAdmin,loadReplenishmentRequests]);
 const reviewReplenishmentRequest=async(id:number,decision:'approve'|'reject')=>{const reason=decision==='reject'?window.prompt('Nhập lý do từ chối yêu cầu nhập:'):'';if(decision==='reject'&&!reason?.trim())return;try{await api.post(`/khohang/replenishment-requests/${id}/decision`,{decision,reason:reason?.trim()});setNotice(decision==='approve'?'Đã duyệt đề nghị nhập. Tồn kho chưa thay đổi.':'Đã từ chối đề nghị nhập.');await loadReplenishmentRequests()}catch(e){setRequestError(message(e))}};
 const cards=[['📦','Tổng tồn kho',dashboard?.stats.tongTon?.toLocaleString('vi-VN')],['🪙','Giá trị tồn kho',formatCurrency(dashboard?.stats.giaTriTonKho||0)],['⚠️','Sắp hết hàng',dashboard?.stats.sapHet],['◷','Sắp hết hạn',dashboard?.stats.sapHetHan],['▣','Phiếu chờ xác nhận',dashboard?.stats.phieuChoXacNhan]];
 return <div className="space-y-4 text-slate-800">
  {isAdmin&&<section className="rounded-2xl border border-amber-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-bold">Yêu cầu nhập hàng của nhân viên</h2><p className="text-xs text-slate-500">Duyệt đề nghị không tự cộng tồn; chỉ phiếu nhận hàng xác nhận mới thay đổi kho.</p></div><button onClick={()=>void loadReplenishmentRequests()} className="text-sm font-semibold text-blue-700">Làm mới</button></div>{requestError&&<p className="mb-2 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{requestError}</p>}{replenishmentRequests.length===0?<p className="text-sm text-slate-500">Không có yêu cầu đang chờ duyệt.</p>:replenishmentRequests.map(r=><div key={r.Id} className="flex flex-wrap items-center justify-between gap-3 border-t py-3"><div className="min-w-60 flex-1"><b>YC#{r.Id} · {r.NguoiYeuCau}</b><p className="text-sm">{r.SanPhamDau||'Sản phẩm'}{Number(r.SoDong)>1?` +${Number(r.SoDong)-1}`:''} · {r.LyDo}</p><small className="text-slate-500">{new Date(r.NgayTao).toLocaleString('vi-VN')}</small></div><div className="flex gap-2"><button onClick={()=>void reviewReplenishmentRequest(r.Id,'reject')} className="rounded-lg border border-rose-300 px-3 py-2 text-sm text-rose-700">Từ chối</button><button onClick={()=>void reviewReplenishmentRequest(r.Id,'approve')} className="rounded-lg bg-amber-400 px-3 py-2 text-sm font-bold">Duyệt đề nghị</button></div></div>)}</section>}
  <div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm text-slate-500">Kho hàng / <b>Tổng quan</b></p><h1 className="text-3xl font-bold">Quản lý kho hàng</h1><p className="text-slate-500">Theo dõi tồn kho, lô hàng và hạn sử dụng</p></div><div className="flex gap-3"><button onClick={openCount} className="rounded-xl border bg-white px-5 py-3 font-semibold">▣ Kiểm kê kho</button><button onClick={openReceipt} className="rounded-xl bg-amber-600 px-5 py-3 font-semibold text-white">＋ Tạo phiếu nhập</button></div></div>
  {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{error} <button onClick={load} className="underline">Thử lại</button></div>}{notice&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-700">{notice}<button onClick={()=>setNotice('')} className="float-right">✕</button></div>}
  <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{cards.map(([i,t,v])=><div key={String(t)} className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-sm text-slate-500">{i} {t}</p><b className="text-2xl">{loading?'…':String(v??0)}</b></div>)}</div>
  <div className="grid gap-4 xl:grid-cols-[1.5fr_1fr]"><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="mb-4 font-bold">Nhập – xuất kho 6 tháng</h2><div className="flex h-36 items-end justify-around border-b">{(dashboard?.chart||[]).map((x:any)=><div key={x.thang} className="flex h-full items-end gap-1"><i className="w-6 bg-blue-500" style={{height:`${Math.max(2,Math.min(100,Number(x.nhap)))}%`}}/><i className="w-6 bg-pink-400" style={{height:`${Math.max(2,Math.min(100,Number(x.xuat)))}%`}}/></div>)}</div></section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="mb-3 font-bold">Cảnh báo cần xử lý</h2>{(dashboard?.alerts||[]).slice(0,4).map((a:any)=><button onClick={()=>{setTab('expiry');setPage(1)}} key={`${a.MaSanPham}-${a.MaLoCode}`} className="mb-2 block w-full rounded-xl bg-rose-50 p-3 text-left"><b className="text-rose-600">{a.LoaiCanhBao}</b><p>{a.TenSanPham} · {a.MaLoCode}</p></button>)}{!dashboard?.alerts?.length&&<p className="text-slate-400">Không có cảnh báo.</p>}</section></div>
  <section className="rounded-2xl bg-white shadow-sm"><div className="flex flex-wrap gap-6 border-b px-5 pt-4">{([['items','Tồn kho hiện tại'],['lots','Theo lô'],['expiry','Sắp hết hạn'],['moves','Biến động gần đây']] as const).map(([key,label])=><button key={key} onClick={()=>{setTab(key);setPage(1)}} className={`border-b-2 pb-3 ${tab===key?'border-rose-500 text-rose-600':'border-transparent text-slate-500'}`}>{label}</button>)}</div><div className="flex flex-wrap gap-3 p-4"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Tìm tên, SKU hoặc mã lô" className="min-w-72 rounded-xl border px-4 py-2"/><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}} className="rounded-xl border px-4"><option value="">Tất cả danh mục</option>{categories.map(x=><option key={x.MaDanhMuc} value={x.MaDanhMuc}>{x.TenDanhMuc}</option>)}</select>{tab==='items'&&<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="rounded-xl border px-4"><option value="">Tất cả trạng thái</option><option>Ổn định</option><option>Sắp hết</option><option>Hết hàng</option></select>}</div>
   <div className="overflow-x-auto">{tab==='items'?<table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{['Sản phẩm','SKU','Tồn thực tế','Đã giữ','Có thể bán','Lô gần hết hạn','Vị trí','Trạng thái',''].map(x=><th key={x} className="px-4 py-3 text-left">{x}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.MaSanPham} className="border-t"><td className="px-4 py-3 font-semibold">{x.TenSanPham}</td><td>{x.MaSKU||'—'}</td><td>{x.TonThucTe}</td><td>{x.DaGiu}</td><td className="font-bold">{x.CoTheBan}</td><td>{fmt(x.HanGanNhat)}</td><td>{x.ViTri||'—'}</td><td>{x.TrangThai}</td><td><button onClick={()=>showDetail(x.MaSanPham)} title="Xem chi tiết">◉</button></td></tr>)}</tbody></table>:tab==='moves'?<table className="min-w-full text-sm"><thead><tr>{['Thời gian','Sản phẩm','Lô','Loại','Số lượng','Trước','Sau','Người thực hiện'].map(x=><th key={x} className="px-4 py-3 text-left">{x}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.MaBienDong} className="border-t"><td className="px-4 py-3">{new Date(x.NgayTao).toLocaleString('vi-VN')}</td><td>{x.TenSanPham}</td><td>{x.MaLoCode||'—'}</td><td>{x.Loai}</td><td className={x.SoLuong>=0?'text-emerald-600':'text-rose-600'}>{x.SoLuong>0?'+':''}{x.SoLuong}</td><td>{x.TonTruoc}</td><td>{x.TonSau}</td><td>{x.NguoiThucHien||'Hệ thống'}</td></tr>)}</tbody></table>:<table className="min-w-full text-sm"><thead><tr>{['Sản phẩm','SKU','Mã lô','Ngày sản xuất','Hạn sử dụng','Tồn','Đã giữ','Có thể bán','Vị trí','Trạng thái'].map(x=><th key={x} className="px-4 py-3 text-left">{x}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.MaLo} className="border-t"><td className="px-4 py-3 font-semibold">{x.TenSanPham}</td><td>{x.MaSKU||'—'}</td><td>{x.MaLoCode}</td><td>{fmt(x.NgaySanXuat)}</td><td>{fmt(x.HanSuDung)}</td><td>{x.SoLuongTon}</td><td>{x.SoLuongDaGiu}</td><td>{x.CoTheBan}</td><td>{x.ViTri||'—'}</td><td>{x.TrangThaiHan}</td></tr>)}</tbody></table>}{!loading&&!rows.length&&<p className="p-10 text-center text-slate-400">Không có dữ liệu phù hợp.</p>}</div><div className="flex justify-end gap-3 p-4"><button disabled={page<=1} onClick={()=>setPage(page-1)}>‹</button><b>{page} / {pages}</b><button disabled={page>=pages} onClick={()=>setPage(page+1)}>›</button></div></section>
  {receiptOpen&&<Modal title="Tạo phiếu nhập" onClose={()=>setReceiptOpen(false)}><div className="grid gap-4 md:grid-cols-3"><label>Nhà cung cấp<select value={receipt.MaNCC} onChange={e=>setReceipt({...receipt,MaNCC:e.target.value})} className="mt-1 w-full rounded border p-2"><option value="">Chưa chọn</option>{suppliers.map(x=><option key={x.MaNCC} value={x.MaNCC}>{x.TenNCC}</option>)}</select></label><label>Ngày nhập<input type="date" value={receipt.NgayNhap} onChange={e=>setReceipt({...receipt,NgayNhap:e.target.value})} className="mt-1 w-full rounded border p-2"/></label><label>Ghi chú<input value={receipt.GhiChu} onChange={e=>setReceipt({...receipt,GhiChu:e.target.value})} className="mt-1 w-full rounded border p-2"/></label></div>{receipt.items.map((it:any,index:number)=><div key={index} className="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-4"><label>Sản phẩm<select value={it.MaSanPham} onChange={e=>{const a=[...receipt.items];a[index]={...it,MaSanPham:e.target.value};setReceipt({...receipt,items:a})}} className="w-full rounded border p-2"><option value="">Chọn sản phẩm</option>{products.map(x=><option key={x.MaSanPham} value={x.MaSanPham}>{x.TenSanPham}</option>)}</select></label>{[['MaLoCode','Mã lô','text'],['NgaySanXuat','Ngày sản xuất','date'],['HanSuDung','Hạn sử dụng','date'],['SoLuong','Số lượng','number'],['GiaNhap','Giá nhập','number'],['ViTri','Vị trí kho','text']].map(([k,l,t])=><label key={k}>{l}<input type={t} value={it[k]} onChange={e=>{const a=[...receipt.items];a[index]={...it,[k]:t==='number'?Number(e.target.value):e.target.value};setReceipt({...receipt,items:a})}} className="w-full rounded border p-2"/></label>)}</div>)}<button onClick={()=>setReceipt({...receipt,items:[...receipt.items,{MaSanPham:'',MaLoCode:'',NgaySanXuat:'',HanSuDung:'',SoLuong:1,GiaNhap:0,ViTri:''}]})} className="mt-3 text-rose-600">＋ Thêm sản phẩm</button><div className="mt-5 flex justify-end gap-3"><button onClick={()=>setReceiptOpen(false)} className="rounded border px-5 py-2">Hủy</button><button onClick={()=>saveReceipt(false)} className="rounded border px-5 py-2">Lưu nháp</button><button onClick={()=>saveReceipt(true)} className="rounded bg-rose-600 px-5 py-2 text-white">Gửi xác nhận</button></div>{isAdmin&&receipts.some(x=>x.TrangThai==='Chờ xác nhận')&&<div className="mt-6 border-t pt-4"><h3 className="font-bold">Phiếu chờ xác nhận</h3>{receipts.filter(x=>x.TrangThai==='Chờ xác nhận').map(x=><div key={x.MaPhieuNhap} className="flex justify-between py-2"><span>PN#{x.MaPhieuNhap} · {x.SoDong} dòng · {x.TenNCC||'Chưa có NCC'}</span><button onClick={()=>confirmReceipt(x.MaPhieuNhap)} className="text-emerald-600">Xác nhận nhập kho</button></div>)}</div>}</Modal>}
  {countOpen&&<Modal title="Kiểm kê kho" onClose={()=>setCountOpen(false)}><div className="grid gap-4 md:grid-cols-2"><label>Sản phẩm / lô<select value={countForm.MaLo} onChange={e=>{const lot=allLots.find(x=>String(x.MaLo)===e.target.value);setCountForm({...countForm,MaLo:e.target.value,TonThucTe:Number(lot?.SoLuongTon||0)})}} className="mt-1 w-full rounded border p-2"><option value="">Chọn lô</option>{allLots.map(x=><option key={x.MaLo} value={x.MaLo}>{x.TenSanPham} · {x.MaLoCode}</option>)}</select></label><label>Tồn hệ thống<input readOnly value={selectedLot?.SoLuongTon??''} className="mt-1 w-full rounded border bg-slate-100 p-2"/></label><label>Số lượng thực tế<input type="number" min="0" value={countForm.TonThucTe} onChange={e=>setCountForm({...countForm,TonThucTe:Number(e.target.value)})} className="mt-1 w-full rounded border p-2"/></label><label>Chênh lệch<input readOnly value={selectedLot?countForm.TonThucTe-selectedLot.SoLuongTon:0} className="mt-1 w-full rounded border bg-slate-100 p-2"/></label><label className="md:col-span-2">Lý do<input value={countForm.LyDo} onChange={e=>setCountForm({...countForm,LyDo:e.target.value})} className="mt-1 w-full rounded border p-2"/></label><label className="md:col-span-2">Ghi chú<input value={countForm.GhiChu} onChange={e=>setCountForm({...countForm,GhiChu:e.target.value})} className="mt-1 w-full rounded border p-2"/></label></div><div className="mt-5 flex justify-end gap-3"><button onClick={()=>setCountOpen(false)}>Hủy</button><button onClick={()=>saveCount(false)} className="rounded border px-5 py-2">Lưu phiếu</button><button onClick={()=>saveCount(true)} className="rounded bg-rose-600 px-5 py-2 text-white">Gửi xác nhận</button></div>{isAdmin&&counts.some(x=>x.TrangThai==='Chờ xác nhận')&&<div className="mt-6 border-t pt-4"><h3 className="font-bold">Kiểm kê chờ xác nhận</h3>{counts.filter(x=>x.TrangThai==='Chờ xác nhận').map(x=><div key={x.MaPhieuKiemKe} className="flex justify-between py-2"><span>KK#{x.MaPhieuKiemKe} · {x.LyDo}</span><button onClick={()=>confirmCount(x.MaPhieuKiemKe)} className="text-emerald-600">Xác nhận điều chỉnh</button></div>)}</div>}</Modal>}
  {detail&&<Modal title={`Chi tiết kho · ${detail.product.TenSanPham}`} onClose={()=>setDetail(null)}><div className="grid grid-cols-3 gap-3"><b>Tồn thực tế: {detail.product.TonThucTe}</b><b>Đã giữ: {detail.product.DaGiu}</b><b>Có thể bán: {detail.product.CoTheBan}</b></div><h3 className="mt-5 font-bold">Các lô</h3>{detail.lots.map((x:any)=><p key={x.MaLo} className="border-b py-2">{x.MaLoCode} · tồn {x.SoLuongTon} · giữ {x.SoLuongDaGiu} · HSD {fmt(x.HanSuDung)} · {x.ViTri||'Chưa có vị trí'}</p>)}<h3 className="mt-5 font-bold">Biến động gần đây</h3>{detail.transactions.map((x:any)=><p key={x.MaBienDong} className="border-b py-2">{new Date(x.NgayTao).toLocaleString('vi-VN')} · {x.Loai} · {x.SoLuong>0?'+':''}{x.SoLuong} · {x.GhiChu}</p>)}</Modal>}
 </div>;
}
