/* Additive inventory foundation. Existing product stock is preserved as opening stock. */
SET XACT_ABORT ON;
BEGIN TRY
  BEGIN TRANSACTION;
  IF OBJECT_ID('dbo.NhaCungCap','U') IS NULL CREATE TABLE dbo.NhaCungCap(
    MaNCC INT IDENTITY(1,1) PRIMARY KEY, TenNCC NVARCHAR(200) NOT NULL, SoDienThoai VARCHAR(30) NULL,
    Email VARCHAR(150) NULL, DiaChi NVARCHAR(500) NULL, GhiChu NVARCHAR(1000) NULL,
    TrangThai BIT NOT NULL CONSTRAINT DF_NCC_TrangThai DEFAULT 1, NgayTao DATETIME NOT NULL CONSTRAINT DF_NCC_NgayTao DEFAULT GETDATE());
  IF OBJECT_ID('dbo.LoSanPham','U') IS NULL CREATE TABLE dbo.LoSanPham(
    MaLo INT IDENTITY(1,1) PRIMARY KEY, MaSanPham INT NOT NULL, MaNCC INT NULL, MaLoCode VARCHAR(80) NOT NULL,
    NgaySanXuat DATE NULL, HanSuDung DATE NULL, ViTri NVARCHAR(80) NULL, GiaNhap DECIMAL(18,2) NOT NULL CONSTRAINT DF_Lo_GiaNhap DEFAULT 0,
    SoLuongTon INT NOT NULL CONSTRAINT DF_Lo_Ton DEFAULT 0, SoLuongDaGiu INT NOT NULL CONSTRAINT DF_Lo_Giu DEFAULT 0,
    TrangThai NVARCHAR(30) NOT NULL CONSTRAINT DF_Lo_TrangThai DEFAULT N'Đang dùng', NgayTao DATETIME NOT NULL CONSTRAINT DF_Lo_NgayTao DEFAULT GETDATE(),
    CONSTRAINT FK_Lo_SanPham FOREIGN KEY(MaSanPham) REFERENCES dbo.SanPham(MaSanPham), CONSTRAINT FK_Lo_NCC FOREIGN KEY(MaNCC) REFERENCES dbo.NhaCungCap(MaNCC),
    CONSTRAINT CK_Lo_SoLuong CHECK(SoLuongTon>=0 AND SoLuongDaGiu>=0 AND SoLuongDaGiu<=SoLuongTon));
  IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='UX_LoSanPham_Code' AND object_id=OBJECT_ID('dbo.LoSanPham')) CREATE UNIQUE INDEX UX_LoSanPham_Code ON dbo.LoSanPham(MaSanPham,MaLoCode);
  IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_LoSanPham_FEFO' AND object_id=OBJECT_ID('dbo.LoSanPham')) CREATE INDEX IX_LoSanPham_FEFO ON dbo.LoSanPham(MaSanPham,HanSuDung,SoLuongTon);
  IF OBJECT_ID('dbo.PhieuNhapKho','U') IS NULL CREATE TABLE dbo.PhieuNhapKho(
    MaPhieuNhap INT IDENTITY(1,1) PRIMARY KEY, MaNCC INT NULL, MaTaiKhoanTao INT NULL, MaThamChieu UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_PhieuNhap_Ref DEFAULT NEWID(),
    NgayNhap DATETIME NOT NULL CONSTRAINT DF_PhieuNhap_Ngay DEFAULT GETDATE(), TrangThai NVARCHAR(30) NOT NULL CONSTRAINT DF_PhieuNhap_Status DEFAULT N'Nháp', GhiChu NVARCHAR(1000) NULL, TongTien DECIMAL(18,2) NOT NULL CONSTRAINT DF_PhieuNhap_Tong DEFAULT 0,
    CONSTRAINT UX_PhieuNhap_Ref UNIQUE(MaThamChieu), CONSTRAINT FK_PhieuNhap_NCC FOREIGN KEY(MaNCC) REFERENCES dbo.NhaCungCap(MaNCC), CONSTRAINT FK_PhieuNhap_TK FOREIGN KEY(MaTaiKhoanTao) REFERENCES dbo.TaiKhoan(MaTaiKhoan));
  IF OBJECT_ID('dbo.ChiTietPhieuNhap','U') IS NULL CREATE TABLE dbo.ChiTietPhieuNhap(
    MaChiTietNhap INT IDENTITY(1,1) PRIMARY KEY, MaPhieuNhap INT NOT NULL, MaSanPham INT NOT NULL, MaLoCode VARCHAR(80) NOT NULL, NgaySanXuat DATE NULL, HanSuDung DATE NULL, ViTri NVARCHAR(80) NULL, SoLuong INT NOT NULL, GiaNhap DECIMAL(18,2) NOT NULL,
    CONSTRAINT FK_CTPN_Phieu FOREIGN KEY(MaPhieuNhap) REFERENCES dbo.PhieuNhapKho(MaPhieuNhap), CONSTRAINT FK_CTPN_SP FOREIGN KEY(MaSanPham) REFERENCES dbo.SanPham(MaSanPham), CONSTRAINT CK_CTPN_SoLuong CHECK(SoLuong>0), CONSTRAINT CK_CTPN_Gia CHECK(GiaNhap>=0));
  IF OBJECT_ID('dbo.BienDongKho','U') IS NULL CREATE TABLE dbo.BienDongKho(
    MaBienDong INT IDENTITY(1,1) PRIMARY KEY, MaSanPham INT NOT NULL, MaLo INT NULL, Loai NVARCHAR(40) NOT NULL, SoLuong INT NOT NULL, TonTruoc INT NOT NULL, TonSau INT NOT NULL,
    MaHoaDon INT NULL, MaPhieuNhap INT NULL, MaTaiKhoan INT NULL, MaThamChieu UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_BienDong_Ref DEFAULT NEWID(), GhiChu NVARCHAR(1000) NULL, NgayTao DATETIME NOT NULL CONSTRAINT DF_BienDong_Ngay DEFAULT GETDATE(),
    CONSTRAINT UX_BienDong_Ref UNIQUE(MaThamChieu), CONSTRAINT FK_BienDong_SP FOREIGN KEY(MaSanPham) REFERENCES dbo.SanPham(MaSanPham), CONSTRAINT FK_BienDong_Lo FOREIGN KEY(MaLo) REFERENCES dbo.LoSanPham(MaLo), CONSTRAINT FK_BienDong_HD FOREIGN KEY(MaHoaDon) REFERENCES dbo.HoaDon(MaHoaDon), CONSTRAINT FK_BienDong_PN FOREIGN KEY(MaPhieuNhap) REFERENCES dbo.PhieuNhapKho(MaPhieuNhap));
  IF OBJECT_ID('dbo.GiuHangDonHang','U') IS NULL CREATE TABLE dbo.GiuHangDonHang(
    MaGiuHang INT IDENTITY(1,1) PRIMARY KEY, MaHoaDon INT NOT NULL, MaLo INT NOT NULL, SoLuong INT NOT NULL, TrangThai NVARCHAR(20) NOT NULL CONSTRAINT DF_GiuHang_Status DEFAULT N'Đang giữ', HetHanLuc DATETIME NULL, NgayTao DATETIME NOT NULL CONSTRAINT DF_GiuHang_Ngay DEFAULT GETDATE(),
    CONSTRAINT FK_GiuHang_HD FOREIGN KEY(MaHoaDon) REFERENCES dbo.HoaDon(MaHoaDon), CONSTRAINT FK_GiuHang_Lo FOREIGN KEY(MaLo) REFERENCES dbo.LoSanPham(MaLo), CONSTRAINT CK_GiuHang_SoLuong CHECK(SoLuong>0));
  IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_BienDongKho_Ngay' AND object_id=OBJECT_ID('dbo.BienDongKho')) CREATE INDEX IX_BienDongKho_Ngay ON dbo.BienDongKho(NgayTao DESC,MaSanPham);
  IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_GiuHangDonHang_Status' AND object_id=OBJECT_ID('dbo.GiuHangDonHang')) CREATE INDEX IX_GiuHangDonHang_Status ON dbo.GiuHangDonHang(MaHoaDon,TrangThai);
  COMMIT TRANSACTION;
END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK TRANSACTION; THROW; END CATCH;
