import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect, useLocalSearchParams } from "expo-router";
import React, { useCallback, useState } from "react";
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAuth } from "@/nguon/AuthContext";
import { setCheckoutAddressChoice } from "@/nguon/checkoutAddressSelection";
import { DiaChiInput, DiaChiNhanHang, khachHangService } from "@/dich_vu/khachHang";

export default function DiaChiScreen(){
 const {token}=useAuth();const params=useLocalSearchParams<{mode?:string}>();const selectionMode=params.mode==="select";const [rows,setRows]=useState<DiaChiNhanHang[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [formOpen,setFormOpen]=useState(false);const [editing,setEditing]=useState<number|null>(null);const [name,setName]=useState("");const [phone,setPhone]=useState("");const [address,setAddress]=useState("");const [makeDefault,setMakeDefault]=useState(false);
 const load=useCallback(async()=>{if(!token){setLoading(false);return}setLoading(true);setError("");try{const r=await khachHangService.danhSachDiaChi(token);setRows(r.data)}catch(e:any){setError(e?.message||"Không thể tải địa chỉ")}finally{setLoading(false)}},[token]);useFocusEffect(useCallback(()=>{void load()},[load]));
 function begin(row?:DiaChiNhanHang){setEditing(row?.Id||null);setName(row?.TenNguoiNhan||"");setPhone(row?.SoDienThoai||"");setAddress(row?.DiaChi||"");setMakeDefault(Boolean(row?.MacDinh));setFormOpen(true);setError("")}
 function useForCheckout(row:DiaChiNhanHang){if(!token)return;setCheckoutAddressChoice(token,row.Id);router.back()}
 async function save(){if(!token)return;const cleanPhone=phone.replace(/[ .-]/g,"");if(!name.trim()||!address.trim()||!/^(03|05|07|08|09)\d{8}$/.test(cleanPhone)){setError("Nhập người nhận, số điện thoại Việt Nam 10 chữ số và địa chỉ đầy đủ.");return}setSaving(true);setError("");try{const payload:DiaChiInput={TenNguoiNhan:name.trim(),SoDienThoai:cleanPhone,DiaChi:address.trim(),MacDinh:makeDefault};if(editing){await khachHangService.suaDiaChi(editing,payload,token);if(makeDefault)await khachHangService.datDiaChiMacDinh(editing,token)}else await khachHangService.themDiaChi(payload,token);setFormOpen(false);await load()}catch(e:any){setError(e?.message||"Không thể lưu địa chỉ")}finally{setSaving(false)}}
 function remove(row:DiaChiNhanHang){Alert.alert("Xóa địa chỉ", "Địa chỉ đã dùng trong đơn hàng cũ vẫn được giữ nguyên theo thông tin lúc đặt.", [{text:"Hủy",style:"cancel"},{text:"Xóa",style:"destructive",onPress:async()=>{try{if(token)await khachHangService.xoaDiaChi(row.Id,token);await load()}catch(e:any){setError(e?.message||"Không thể xóa địa chỉ")}}}])}
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}><View style={s.header}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="arrow-back" size={23} color="#173E32"/></TouchableOpacity><Text style={s.title}>Địa chỉ nhận hàng</Text><TouchableOpacity onPress={()=>void load()}><Ionicons name="refresh" size={22} color="#176A50"/></TouchableOpacity></View>
 <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">{selectionMode?<Text style={s.muted}>Chọn địa chỉ chỉ áp dụng cho đơn hàng hiện tại; không thay đổi địa chỉ mặc định trong hồ sơ.</Text>:null}{error?<View style={s.error}><Text style={s.errorText}>{error}</Text><TouchableOpacity onPress={()=>void load()}><Text style={s.link}>Thử lại</Text></TouchableOpacity></View>:null}
 {loading?<View style={s.center}><ActivityIndicator color="#176A50"/><Text style={s.muted}>Đang tải địa chỉ…</Text></View>:rows.length===0&&!formOpen?<View style={s.empty}><Ionicons name="location-outline" size={45} color="#D97B3B"/><Text style={s.section}>Chưa có địa chỉ nhận hàng</Text><Text style={s.muted}>Thêm địa chỉ để dùng nhanh khi thanh toán.</Text></View>:rows.map(row=><View key={row.Id} style={s.card}><View style={s.pin}><Ionicons name="location" size={22} color="#E67B37"/></View><View style={{flex:1}}><View style={s.nameLine}><Text style={s.name}>{row.TenNguoiNhan}</Text>{row.MacDinh?<Text style={s.badge}>Mặc định</Text>:null}</View><Text style={s.muted}>{row.SoDienThoai}</Text><Text style={s.address}>{row.DiaChi}</Text></View>{selectionMode?<TouchableOpacity style={s.selectButton} onPress={()=>useForCheckout(row)}><Text style={s.selectButtonText}>Dùng địa chỉ này</Text></TouchableOpacity>:<><TouchableOpacity onPress={()=>begin(row)}><Ionicons name="create-outline" size={21} color="#43564D"/></TouchableOpacity><TouchableOpacity onPress={()=>remove(row)}><Ionicons name="trash-outline" size={19} color="#C95F42"/></TouchableOpacity>{!row.MacDinh&&<TouchableOpacity style={s.defaultButton} onPress={async()=>{try{if(token)await khachHangService.datDiaChiMacDinh(row.Id,token);await load()}catch(e:any){setError(e?.message||"Không thể đặt mặc định")}}}><Text style={s.link}>Đặt mặc định</Text></TouchableOpacity>}</>}</View>)}
 {formOpen?<View style={s.form}><View style={s.between}><Text style={s.section}>{editing?"Sửa địa chỉ":"Thêm địa chỉ"}</Text><TouchableOpacity onPress={()=>setFormOpen(false)}><Ionicons name="close" size={23} color="#33433D"/></TouchableOpacity></View><TextInput style={s.input} value={name} onChangeText={setName} placeholder="Họ và tên người nhận"/><TextInput style={s.input} value={phone} onChangeText={setPhone} placeholder="Số điện thoại" keyboardType="phone-pad"/><Text style={s.muted}>Nhập địa chỉ đầy đủ theo địa giới thực tế (tỉnh/thành, quận/huyện, phường/xã và số nhà/đường). Các phần được lưu nguyên văn, không ép chọn danh mục địa giới.</Text><TextInput style={[s.input,s.multiline]} value={address} onChangeText={setAddress} placeholder="Số nhà, đường, phường/xã, quận/huyện, tỉnh/thành" multiline/><TouchableOpacity style={s.checkRow} onPress={()=>setMakeDefault(!makeDefault)}><Ionicons name={makeDefault?"checkbox":"square-outline"} size={22} color="#176A50"/><Text style={s.address}>Đặt làm địa chỉ mặc định</Text></TouchableOpacity><TouchableOpacity disabled={saving} style={s.primary} onPress={()=>void save()}><Text style={s.primaryText}>{saving?"Đang lưu…":"Lưu địa chỉ"}</Text></TouchableOpacity></View>:<TouchableOpacity style={s.add} onPress={()=>begin()}><Ionicons name="add-circle-outline" size={21} color="#176A50"/><Text style={s.link}>Thêm địa chỉ</Text></TouchableOpacity>}
 </ScrollView></KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F6FAF7"},header:{height:56,paddingHorizontal:16,backgroundColor:"white",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{fontSize:18,fontWeight:"800",color:"#153D32"},content:{padding:15,paddingBottom:35,gap:12},center:{alignItems:"center",padding:30,gap:10},empty:{alignItems:"center",padding:35,backgroundColor:"white",borderRadius:16,gap:8},muted:{fontSize:13,color:"#6D7A74",lineHeight:19},section:{fontSize:16,fontWeight:"800",color:"#173E32"},card:{backgroundColor:"white",padding:13,borderRadius:15,borderWidth:1,borderColor:"#E5EEE8",flexDirection:"row",alignItems:"flex-start",gap:10,flexWrap:"wrap"},pin:{width:30,alignItems:"center",paddingTop:4},nameLine:{flexDirection:"row",alignItems:"center",gap:8},name:{fontWeight:"800",color:"#1C2E27",fontSize:14},badge:{fontSize:10,fontWeight:"700",color:"#176A50",backgroundColor:"#DEF2E7",paddingHorizontal:8,paddingVertical:4,borderRadius:10},address:{fontSize:13,color:"#384740",marginTop:5,lineHeight:19},defaultButton:{marginLeft:39},link:{fontWeight:"700",color:"#176A50"},selectButton:{width:"100%",minHeight:40,alignItems:"center",justifyContent:"center",backgroundColor:"#E7F5EC",borderRadius:10},selectButtonText:{fontWeight:"800",color:"#176A50"},add:{height:50,backgroundColor:"white",borderRadius:13,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8,borderWidth:1,borderColor:"#DCE9E0"},form:{padding:15,backgroundColor:"white",borderRadius:15,gap:10,borderWidth:1,borderColor:"#DDE9E1"},between:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},input:{borderWidth:1,borderColor:"#DDE5E0",borderRadius:11,minHeight:46,paddingHorizontal:12,color:"#20332A"},multiline:{minHeight:90,textAlignVertical:"top",paddingTop:12},checkRow:{flexDirection:"row",alignItems:"center",gap:9},primary:{backgroundColor:"#176A50",minHeight:49,borderRadius:12,alignItems:"center",justifyContent:"center"},primaryText:{color:"white",fontWeight:"800",fontSize:15},error:{backgroundColor:"#FFF0EF",padding:12,borderRadius:11},errorText:{color:"#A23A34"}});
