import { useCallback, useEffect, useState } from 'react';
import { voucherAPI, categoriesAPI, productsAPI, customersAPI } from '../../services/api';

type Voucher = { Id:number; MaVoucher:string; TenChuongTrinh:string; LoaiGiam:string; GiaTri:number; GiamToiDa:number|null; DonHangToiThieu:number; TongLuotSuDung:number; LuotDaSuDung:number; LuotDangGiu:number; MoiKhachToiDa:number; PhamVi:string; DoiTuong:string; NgayBatDau:string; NgayKetThuc:string; TrangThai:string; TrangThaiHienThi:string; MoTa?:string; ChoPhepKetHopPhiShip:boolean; TuDongKichHoat:boolean };
const SHOP_TIME_ZONE='Asia/Ho_Chi_Minh';
const localDateTime=(value:string|Date)=>{const d=value instanceof Date?value:new Date(value);if(!Number.isFinite(d.getTime()))return '';const parts=new Intl.DateTimeFormat('en-CA',{timeZone:SHOP_TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d);const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;};
const apiDateTime=(value:string)=>/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value)?`${value}:00+07:00`:'';
const fresh=()=>({MaVoucher:'',TenChuongTrinh:'',MoTa:'',LoaiGiam:'PHAN_TRAM',GiaTri:10,GiamToiDa:'',DonHangToiThieu:0,TongLuotSuDung:100,MoiKhachToiDa:1,NgayBatDau:localDateTime(new Date()),NgayKetThuc:localDateTime(new Date(Date.now()+7*86400000)),PhamVi:'TOAN_BO_DON_HANG',MaDanhMuc:[] as number[],MaSanPham:[] as number[],ThuongHieu:[] as string[],DoiTuong:'TAT_CA_KHACH_HANG',MaKhachHang:[] as number[],ChoPhepKetHopPhiShip:false,TuDongKichHoat:false,TrangThai:'NHAP'});
const labelStatus:Record<string,string>={DANG_HOAT_DONG:'Đang hoạt động',SAP_DIEN_RA:'Sắp diễn ra',TAM_DUNG:'Tạm dừng',HET_LUOT:'Hết lượt',HET_HAN:'Hết hạn',DA_HUY:'Đã hủy',NHAP:'Bản nháp'};
const fmt=(n:any)=>Number(n||0).toLocaleString('vi-VN');
const unwrap=(r:any)=>r?.data?.data??r?.data??[];

export default function Vouchers(){
 const [rows,setRows]=useState<Voucher[]>([]),[stats,setStats]=useState<any>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[tab,setTab]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0);
 const [open,setOpen]=useState(false),[step,setStep]=useState(1),[form,setForm]=useState<any>(fresh()),[editing,setEditing]=useState<number|null>(null),[saving,setSaving]=useState(false),[fieldError,setFieldError]=useState('');
 const [categories,setCategories]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[brands,setBrands]=useState<string[]>([]),[detail,setDetail]=useState<any>(null),[detailRows,setDetailRows]=useState<any[]>([]),[detailOrders,setDetailOrders]=useState<any[]>([]),[detailAudit,setDetailAudit]=useState<any[]>([]),[typeFilter,setTypeFilter]=useState(''),[scopeFilter,setScopeFilter]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [list,summary]=await Promise.all([voucherAPI.getAll({page,limit:8,search:search||undefined,trangThai:tab||undefined,loaiGiam:typeFilter||undefined,phamVi:scopeFilter||undefined}),voucherAPI.getStats()]);const d=unwrap(list);setRows(Array.isArray(d)?d:[]);setTotal(list.data?.pagination?.total||0);setStats(unwrap(summary));}catch(e:any){setError(e.response?.data?.message||e.message||'Không thể tải voucher từ máy chủ');}finally{setLoading(false);}},[page,search,tab,typeFilter,scopeFilter]);
 useEffect(()=>{load();},[load]);
 useEffect(()=>{Promise.all([categoriesAPI.getAll(),productsAPI.getAll({page:1,limit:100}),customersAPI.getAll({page:1,limit:100})]).then(([c,p,k])=>{setCategories(unwrap(c));const pp=unwrap(p);setProducts(Array.isArray(pp)?pp:[]);setBrands([...new Set((Array.isArray(pp)?pp:[]).map((x:any)=>x.ThuongHieu).filter(Boolean))] as string[]);setCustomers(unwrap(k));}).catch(()=>{});},[]);
 const update=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));
 const toggleMulti=(key:'MaDanhMuc'|'MaSanPham'|'MaKhachHang'|'ThuongHieu',value:any)=>setForm((f:any)=>({...f,[key]:f[key].includes(value)?f[key].filter((x:any)=>x!==value):[...f[key],value]}));
 const startNew=()=>{setForm(fresh());setEditing(null);setStep(1);setFieldError('');setOpen(true);};
 const edit=async(id:number)=>{try{const r=await voucherAPI.getById(id);const d=unwrap(r);setForm({...fresh(),...d,NgayBatDau:localDateTime(d.NgayBatDau),NgayKetThuc:localDateTime(d.NgayKetThuc)});setEditing(id);setStep(1);setFieldError('');setOpen(true);}catch(e:any){setError(e.response?.data?.message||'Không tải được chi tiết voucher');}};
 const save=async()=>{setFieldError('');if(!form.MaVoucher.trim()||!form.TenChuongTrinh.trim()){setFieldError('Mã voucher và tên chương trình là bắt buộc');setStep(1);return;}if(!apiDateTime(form.NgayBatDau)||!apiDateTime(form.NgayKetThuc)){setFieldError('Ngày bắt đầu và ngày kết thúc phải nhập đầy đủ.');setStep(2);return;}if(form.NgayBatDau>=form.NgayKetThuc){setFieldError('Ngày bắt đầu phải trước ngày kết thúc.');setStep(2);return;}if(['DANH_MUC','SAN_PHAM','THUONG_HIEU'].includes(form.PhamVi)&&!(form.PhamVi==='DANH_MUC'?form.MaDanhMuc:form.PhamVi==='SAN_PHAM'?form.MaSanPham:form.ThuongHieu).length){setFieldError('Hãy chọn ít nhất một đối tượng áp dụng');setStep(3);return;}setSaving(true);try{const data={...form,NgayBatDau:apiDateTime(form.NgayBatDau),NgayKetThuc:apiDateTime(form.NgayKetThuc),GiamToiDa:form.GiamToiDa===''?null:Number(form.GiamToiDa),GiaTri:Number(form.GiaTri),DonHangToiThieu:Number(form.DonHangToiThieu),TongLuotSuDung:Number(form.TongLuotSuDung),MoiKhachToiDa:Number(form.MoiKhachToiDa)};if(editing)await voucherAPI.update(editing,data);else await voucherAPI.create(data);setOpen(false);await load();}catch(e:any){setFieldError(e.response?.data?.message||'Không thể lưu voucher. Vui lòng kiểm tra ngày giờ và thử lại.');setStep(2);}finally{setSaving(false);}};
 const detailView=async(v:Voucher)=>{try{setDetail(unwrap(await voucherAPI.getById(v.Id)));const [r,o,a]=await Promise.all([voucherAPI.usage(v.Id),voucherAPI.orders(v.Id),voucherAPI.audit(v.Id)]);setDetailRows(unwrap(r));setDetailOrders(unwrap(o));setDetailAudit(unwrap(a));}catch(e:any){setError(e.response?.data?.message||'Không thể tải chi tiết');}};
 const action=async(kind:string,v:Voucher)=>{try{if(kind==='copy')await voucherAPI.copy(v.Id);if(kind==='activate')await voucherAPI.activate(v.Id);if(kind==='pause')await voucherAPI.pause(v.Id);if(kind==='cancel'&&window.confirm(`Hủy voucher ${v.MaVoucher}?`))await voucherAPI.cancel(v.Id);await load();}catch(e:any){setError(e.response?.data?.message||'Thao tác không thành công');}};
 const currency=(v:Voucher)=>v.LoaiGiam==='PHAN_TRAM'?`${v.GiaTri}%${v.GiamToiDa?` tối đa ${fmt(v.GiamToiDa)}đ`:''}`:v.LoaiGiam==='MIEN_GIAM_PHI_SHIP'?`Phí ship đến ${fmt(v.GiaTri)}đ`:`${fmt(v.GiaTri)}đ`;
 const pageCount=Math.max(1,Math.ceil(total/8));
 return <div className="min-h-screen bg-slate-50 p-5 text-slate-800"><div className="mb-5 flex items-end justify-between"><div><div className="mb-2 text-sm text-slate-500">Khuyến mãi　/　Quản lý voucher</div><h1 className="text-3xl font-bold">Quản lý voucher</h1><p className="mt-1 text-slate-500">Tạo chương trình, kiểm soát lượt dùng và hiệu quả ưu đãi</p></div><button onClick={startNew} className="rounded-lg bg-pink-600 px-5 py-3 font-semibold text-white shadow">＋ Tạo voucher</button></div>
 <div className="mb-5 grid grid-cols-2 gap-3 xl:grid-cols-5">{[['Đang hoạt động',stats.DangHoatDong,'#16a34a'],['Sắp diễn ra',stats.SapDienRa,'#2563eb'],['Hết hạn',stats.HetHan,'#dc2626'],['Lượt dùng hôm nay',stats.LuotDungHomNay,'#7c3aed'],['Tổng giảm tháng này',`${fmt(stats.TongGiamThang)}đ`,'#d97706']].map(([t,n,c]:any)=><div key={t} className="rounded-xl border border-slate-100 bg-white p-4 shadow-sm"><div className="text-sm text-slate-500">{t}</div><div className="mt-1 text-2xl font-bold" style={{color:c}}>{n??'—'}</div></div>)}</div>
 <div className="mb-3 flex gap-5 border-b bg-white px-4">{[['','Tất cả'],['DANG_HOAT_DONG','Đang hoạt động'],['SAP_DIEN_RA','Sắp diễn ra'],['TAM_DUNG','Tạm dừng'],['HET_HAN','Hết hạn']].map(([id,title])=><button key={id} onClick={()=>{setTab(id);setPage(1);}} className={`border-b-2 px-1 py-3 text-sm ${tab===id?'border-pink-600 font-bold text-pink-600':'border-transparent text-slate-500'}`}>{title}</button>)}</div>
  <div className="mb-3 flex flex-wrap gap-3 rounded-xl bg-white p-3"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="⌕  Tìm mã hoặc tên voucher" className="w-full max-w-md rounded-lg border p-3 outline-pink-400"/><select value={typeFilter} onChange={e=>{setTypeFilter(e.target.value);setPage(1);}} className="rounded-lg border px-4"><option value="">Loại giảm</option><option value="PHAN_TRAM">Phần trăm</option><option value="SO_TIEN_CO_DINH">Số tiền cố định</option><option value="MIEN_GIAM_PHI_SHIP">Phí vận chuyển</option></select><select value={scopeFilter} onChange={e=>{setScopeFilter(e.target.value);setPage(1);}} className="rounded-lg border px-4"><option value="">Phạm vi</option><option value="TOAN_BO_DON_HANG">Toàn bộ đơn hàng</option><option value="DANH_MUC">Danh mục</option><option value="SAN_PHAM">Sản phẩm</option><option value="THUONG_HIEU">Thương hiệu</option><option value="PHI_VAN_CHUYEN">Phí vận chuyển</option></select></div>
 {error&&<div className="mb-3 flex justify-between rounded-lg bg-red-50 p-3 text-red-700">{error}<button onClick={load}>Thử lại</button></div>}
 <div className="overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{['Mã voucher','Chương trình','Loại giảm','Điều kiện','Thời gian','Đã dùng / Tổng lượt','Trạng thái','Thao tác'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={8} className="p-10 text-center">Đang tải dữ liệu voucher…</td></tr>:!rows.length?<tr><td colSpan={8} className="p-10 text-center text-slate-500">Chưa có voucher phù hợp</td></tr>:rows.map(v=><tr key={v.Id} className="border-t hover:bg-pink-50/50"><td className="px-4 py-3 font-bold">{v.MaVoucher}</td><td className="px-4 py-3"><div className="font-semibold">{v.TenChuongTrinh}</div><div className="text-xs text-slate-400">{v.MoTa}</div></td><td className="px-4 py-3">{currency(v)}</td><td className="px-4 py-3">Đơn từ {fmt(v.DonHangToiThieu)}đ</td><td className="px-4 py-3">{new Date(v.NgayBatDau).toLocaleDateString('vi-VN')} – {new Date(v.NgayKetThuc).toLocaleDateString('vi-VN')}</td><td className="min-w-40 px-4 py-3"><div>{v.LuotDaSuDung+v.LuotDangGiu} / {v.TongLuotSuDung}</div><div className="mt-1 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-emerald-500" style={{width:`${Math.min(100,(100*(v.LuotDaSuDung+v.LuotDangGiu)/v.TongLuotSuDung))}%`}}/></div></td><td className="px-4 py-3"><span className="rounded-full bg-pink-50 px-3 py-1 text-xs font-semibold text-pink-700">{labelStatus[v.TrangThaiHienThi]||v.TrangThaiHienThi}</span></td><td className="whitespace-nowrap px-4 py-3"><button className="mr-2 text-pink-600" onClick={()=>detailView(v)}>Xem</button><button className="mr-2 text-slate-600" onClick={()=>edit(v.Id)}>Sửa</button><button className="mr-2 text-slate-600" onClick={()=>action('copy',v)}>Sao chép</button><button className="mr-2 text-slate-600" onClick={()=>action(v.TrangThai==='TAM_DUNG'?'activate':'pause',v)}>{v.TrangThai==='TAM_DUNG'?'Mở lại':'Tạm dừng'}</button><button className="text-rose-600" onClick={()=>action('cancel',v)}>Hủy</button></td></tr>)}</tbody></table><div className="flex items-center justify-between border-t p-3 text-sm text-slate-500"><span>{total} voucher</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(page-1)} className="rounded border px-3 py-1 disabled:opacity-30">‹</button><span>{page} / {pageCount}</span><button disabled={page>=pageCount} onClick={()=>setPage(page+1)} className="rounded border px-3 py-1 disabled:opacity-30">›</button></div></div></div>
 {open&&<div className="fixed inset-0 z-50 flex justify-end bg-slate-900/35"><div className="flex h-full w-full max-w-[520px] flex-col bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><h2 className="text-xl font-bold">{editing?'Cập nhật voucher':'Tạo voucher'}</h2><button onClick={()=>setOpen(false)}>✕</button></div><div className="flex justify-around border-b py-4 text-sm">{['Thông tin','Điều kiện','Phạm vi'].map((x,i)=><button key={x} onClick={()=>setStep(i+1)} className={step===i+1?'font-bold text-pink-600':''}><span className="mr-2 rounded-full bg-slate-100 px-2 py-1">{i+1}</span>{x}</button>)}</div><div className="flex-1 space-y-4 overflow-y-auto p-5">
{step===1&&<><h3 className="font-bold">Thông tin cơ bản</h3><label className="block text-sm">Mã voucher *<input disabled={!!editing&&Boolean(form.LuotDaSuDung+form.LuotDangGiu)} value={form.MaVoucher} onChange={e=>update('MaVoucher',e.target.value.toUpperCase())} className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="block text-sm">Tên chương trình *<input value={form.TenChuongTrinh} onChange={e=>update('TenChuongTrinh',e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="block text-sm">Mô tả<textarea value={form.MoTa} onChange={e=>update('MoTa',e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="block text-sm">Loại giảm<select value={form.LoaiGiam} disabled={!!editing&&Boolean(form.LuotDaSuDung+form.LuotDangGiu)} onChange={e=>update('LoaiGiam',e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"><option value="PHAN_TRAM">Giảm theo phần trăm</option><option value="SO_TIEN_CO_DINH">Giảm số tiền cố định</option><option value="MIEN_GIAM_PHI_SHIP">Giảm phí vận chuyển</option></select></label><label className="block text-sm">Giá trị giảm *<input type="number" min="0" value={form.GiaTri} onChange={e=>update('GiaTri',e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"/></label>{form.LoaiGiam==='PHAN_TRAM'&&<label className="block text-sm">Giảm tối đa (đ)<input type="number" min="0" value={form.GiamToiDa} onChange={e=>update('GiamToiDa',e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"/><span className="mt-1 block text-xs text-slate-500">Giá trị nhập theo đồng: 10 tương đương 10đ, không quy đổi đơn vị.</span></label>}</>}
{step===2&&<><h3 className="font-bold">Điều kiện sử dụng</h3><label className="block text-sm">Đơn hàng tối thiểu<input type="number" value={form.DonHangToiThieu} onChange={e=>update('DonHangToiThieu',e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="block text-sm">Tổng lượt sử dụng<input type="number" min="1" value={form.TongLuotSuDung} onChange={e=>update('TongLuotSuDung',e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="block text-sm">Mỗi khách tối đa<input type="number" min="1" value={form.MoiKhachToiDa} onChange={e=>update('MoiKhachToiDa',e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm">Bắt đầu<input type="datetime-local" value={form.NgayBatDau} onChange={e=>update('NgayBatDau',e.target.value)} className="mt-1 w-full rounded border p-2"/>{fieldError.includes('Ngày bắt đầu')&&<span className="mt-1 block text-xs text-red-600">{fieldError}</span>}</label><label className="text-sm">Kết thúc<input type="datetime-local" value={form.NgayKetThuc} onChange={e=>update('NgayKetThuc',e.target.value)} className="mt-1 w-full rounded border p-2"/>{fieldError.includes('Ngày kết thúc')&&<span className="mt-1 block text-xs text-red-600">{fieldError}</span>}</label></div><p className="text-xs text-slate-500">Thời gian theo múi giờ cửa hàng Việt Nam (UTC+07:00). Voucher hết hiệu lực tại đúng thời điểm kết thúc.</p><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.ChoPhepKetHopPhiShip} onChange={e=>update('ChoPhepKetHopPhiShip',e.target.checked)}/> Cho phép kết hợp voucher phí ship</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.TuDongKichHoat} onChange={e=>update('TuDongKichHoat',e.target.checked)}/> Tự động kích hoạt theo thời gian</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.TrangThai==='NHAP'} onChange={e=>update('TrangThai',e.target.checked?'NHAP':'DANG_HOAT_DONG')}/> Lưu ở trạng thái nháp</label></>}
 {step===3&&<><h3 className="font-bold">Phạm vi áp dụng</h3><label className="block text-sm">Phạm vi<select value={form.PhamVi} onChange={e=>update('PhamVi',e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"><option value="TOAN_BO_DON_HANG">Toàn bộ đơn hàng</option><option value="DANH_MUC">Danh mục</option><option value="SAN_PHAM">Sản phẩm</option><option value="THUONG_HIEU">Thương hiệu</option><option value="PHI_VAN_CHUYEN">Phí vận chuyển</option></select></label>{form.PhamVi==='DANH_MUC'&&<Multi title="Chọn danh mục" rows={categories} keyName="TenDanhMuc" idName="MaDanhMuc" selected={form.MaDanhMuc} onToggle={(v:number)=>toggleMulti('MaDanhMuc',v)}/ >}{form.PhamVi==='SAN_PHAM'&&<Multi title="Chọn sản phẩm" rows={products} keyName="TenSanPham" idName="MaSanPham" selected={form.MaSanPham} onToggle={(v:number)=>toggleMulti('MaSanPham',v)}/ >}{form.PhamVi==='THUONG_HIEU'&&<Multi title="Chọn thương hiệu" rows={brands.map(x=>({TenThuongHieu:x}))} keyName="TenThuongHieu" idName="TenThuongHieu" selected={form.ThuongHieu} onToggle={(v:string)=>toggleMulti('ThuongHieu',v)}/ >}<label className="block text-sm">Đối tượng khách hàng<select value={form.DoiTuong} onChange={e=>update('DoiTuong',e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"><option value="TAT_CA_KHACH_HANG">Tất cả khách hàng</option><option value="KHACH_HANG_MOI">Khách hàng mới</option><option value="KHACH_HANG_CU_THE">Khách hàng cụ thể</option></select></label>{form.DoiTuong==='KHACH_HANG_CU_THE'&&<Multi title="Khách hàng được nhận" rows={customers} keyName="HoTen" idName="MaKhachHang" selected={form.MaKhachHang} onToggle={(v:number)=>toggleMulti('MaKhachHang',v)}/>}<div className="rounded-xl bg-pink-50 p-4"><div className="font-bold text-pink-700">Xem trước voucher</div><div className="mt-2">{form.MaVoucher||'MÃ VOUCHER'} · {form.TenChuongTrinh||'Tên chương trình'}</div><div className="text-sm text-slate-600">{form.LoaiGiam==='PHAN_TRAM'?`${form.GiaTri}%`:form.LoaiGiam==='MIEN_GIAM_PHI_SHIP'?`Giảm phí ship ${fmt(form.GiaTri)}đ`:`Giảm ${fmt(form.GiaTri)}đ`} · Đơn từ {fmt(form.DonHangToiThieu)}đ</div></div></>}
 {fieldError&&<div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{fieldError}</div>}</div><div className="flex justify-between border-t p-4"><button onClick={()=>setOpen(false)} className="rounded-lg border px-4 py-2">Hủy</button><div className="flex gap-2">{step>1&&<button onClick={()=>setStep(step-1)} className="rounded-lg border px-4 py-2">Quay lại</button>}{step<3?<button onClick={()=>{setFieldError('');setStep(step+1)}} className="rounded-lg bg-pink-600 px-4 py-2 text-white">Tiếp tục</button>:<button disabled={saving} onClick={save} className="rounded-lg bg-pink-600 px-4 py-2 font-semibold text-white">{saving?'Đang lưu…':editing?'Cập nhật voucher':'Tạo voucher'}</button>}</div></div></div></div>}
  {detail&&<div className="fixed inset-0 z-[60] flex justify-end bg-slate-900/35"><div className="h-full w-full max-w-md overflow-auto bg-white p-5"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold">Chi tiết {detail.MaVoucher}</h2><button onClick={()=>setDetail(null)}>✕</button></div><div className="rounded-xl bg-pink-50 p-4"><b>{detail.TenChuongTrinh}</b><div className="mt-2">{currency(detail)}</div><div className="text-sm">{detail.MoTa}</div></div><h3 className="mt-5 font-bold">Lịch sử sử dụng</h3>{detailRows.length?detailRows.map((x:any)=><div key={x.Id} className="border-b py-3 text-sm">{x.HoTen} · Đơn #{x.MaHoaDon??'—'} · {x.TrangThai} · {fmt(x.SoTienGiam)}đ</div>):<p className="py-3 text-slate-500">Chưa phát sinh lượt sử dụng</p>}<h3 className="mt-5 font-bold">Đơn hàng áp dụng</h3>{detailOrders.length?detailOrders.map((x:any)=><div key={`${x.MaHoaDon}-${x.LoaiApDung}`} className="border-b py-3 text-sm">Đơn #{x.MaHoaDon} · {x.TrangThai} · giảm {fmt(x.SoTienGiam)}đ</div>):<p className="py-3 text-slate-500">Chưa có đơn hàng</p>}<h3 className="mt-5 font-bold">Nhật ký thay đổi</h3>{detailAudit.length?detailAudit.map((x:any)=><div key={x.Id} className="border-b py-2 text-sm">{x.HanhDong} · {x.NguoiThayDoi} · {new Date(x.CreatedAt).toLocaleString('vi-VN')}</div>):<p className="py-3 text-slate-500">Chưa có lịch sử thay đổi</p>}</div></div>}
 </div>;
}
function Multi({title,rows,keyName,idName,selected,onToggle}:any){return <div><div className="mb-1 text-sm">{title} *</div><div className="max-h-44 space-y-1 overflow-auto rounded-lg border p-2">{rows.map((row:any)=>{const id=row[idName];return <label key={String(id)} className="flex items-center gap-2 rounded p-1 text-sm hover:bg-pink-50"><input type="checkbox" checked={selected.includes(id)} onChange={()=>onToggle(id)}/><span>{row[keyName]||`#${id}`}</span></label>})}</div></div>}
