import {Router,Response} from "express";import multer from "multer";import crypto from "crypto";import fs from "fs/promises";import path from "path";import {AuthRequest,authenticate,authorizeRoles} from "../middleware/auth";import {execute,getPool,query,queryOne,sql} from "../config/database";
const router=Router(),customer=authorizeRoles("KhachHang"),admin=authorizeRoles("Admin"),upload=multer({storage:multer.memoryStorage(),limits:{files:5,fileSize:5*1024*1024}}).array("files",5);
class ReviewError extends Error{constructor(public status:number,message:string){super(message)}}const fail=(res:Response,e:any)=>res.status(e instanceof ReviewError?e.status:500).json({success:false,message:e?.message||"Không thể xử lý đánh giá"});const int=(x:unknown)=>Number.isSafeInteger(Number(x))&&Number(x)>0?Number(x):0;
async function customerId(req:AuthRequest){return (await queryOne<any>("SELECT MaKhachHang FROM KhachHang WHERE MaTaiKhoan=@id",{id:req.user!.MaTaiKhoan}))?.MaKhachHang as number|undefined}
router.get("/san-pham/:id",async(req,res)=>{try{const id=int(req.params.id);if(!id)return res.status(400).json({success:false,message:"Mã sản phẩm không hợp lệ"});const [summary,data]=await Promise.all([queryOne<any>("SELECT COUNT(*) SoDanhGia,CAST(AVG(CAST(SoSao AS decimal(5,2))) AS decimal(4,2)) DiemTrungBinh FROM DanhGiaSanPham WHERE MaSanPham=@id AND TrangThai='HIEN_THI'",{id}),query<any>("SELECT TOP 20 d.SoSao,d.NoiDung,d.NgayTao,LEFT(kh.HoTen,1)+N'***' TenKhachHang FROM DanhGiaSanPham d JOIN KhachHang kh ON kh.MaKhachHang=d.MaKhachHang WHERE d.MaSanPham=@id AND d.TrangThai='HIEN_THI' ORDER BY d.NgayTao DESC",{id})]);res.json({success:true,data:{...summary,danhGia:data}})}catch(e){fail(res,e)}});
router.use(authenticate);
router.get("/cua-toi/co-the-danh-gia",customer,async(req:AuthRequest,res)=>{try{const cid=await customerId(req);if(!cid)return res.status(404).json({success:false,message:"Không tìm thấy hồ sơ khách hàng"});const data=await query<any>(`SELECT hd.MaHoaDon,hd.NgayLap,ct.MaSanPham,COALESCE(ct.TenSanPhamSnapshot,sp.TenSanPham) TenSanPham,COALESCE(ct.HinhAnhSnapshot,sp.HinhAnh) HinhAnh,ct.SoLuong
 FROM HoaDon hd JOIN ChiTietHoaDon ct ON ct.MaHoaDon=hd.MaHoaDon JOIN SanPham sp ON sp.MaSanPham=ct.MaSanPham
 WHERE hd.MaKhachHang=@cid AND hd.TrangThai=N'HOAN_THANH' AND hd.TrangThaiThanhToan=N'DA_THANH_TOAN' AND NOT EXISTS(SELECT 1 FROM DanhGiaSanPham d WHERE d.MaHoaDon=hd.MaHoaDon AND d.MaSanPham=ct.MaSanPham)
 ORDER BY hd.NgayLap DESC`,{cid});res.json({success:true,data})}catch(e){fail(res,e)}});
router.get("/cua-toi",customer,async(req:AuthRequest,res)=>{try{const cid=await customerId(req);if(!cid)return res.status(404).json({success:false,message:"Không tìm thấy hồ sơ khách hàng"});const data=await query<any>(`SELECT d.Id,d.MaHoaDon,d.MaSanPham,d.SoSao,d.NoiDung,d.TrangThai,d.NgayTao,COALESCE(ct.TenSanPhamSnapshot,sp.TenSanPham) TenSanPham,COALESCE(ct.HinhAnhSnapshot,sp.HinhAnh) HinhAnh,(SELECT Url FROM AnhDanhGiaSanPham WHERE DanhGiaId=d.Id FOR JSON PATH) AnhJSON FROM DanhGiaSanPham d JOIN ChiTietHoaDon ct ON ct.MaHoaDon=d.MaHoaDon AND ct.MaSanPham=d.MaSanPham JOIN SanPham sp ON sp.MaSanPham=d.MaSanPham WHERE d.MaKhachHang=@cid ORDER BY d.NgayTao DESC`,{cid});res.json({success:true,data:data.map(x=>({...x,Anh:x.AnhJSON?JSON.parse(x.AnhJSON).map((a:any)=>a.Url):[]}))})}catch(e){fail(res,e)}});
router.post("/",customer,async(req:AuthRequest,res)=>{let tx:sql.Transaction|undefined;try{const cid=await customerId(req),orderId=int(req.body.MaHoaDon),productId=int(req.body.MaSanPham),stars=int(req.body.SoSao),text=String(req.body.NoiDung||"").trim();if(!cid)return res.status(404).json({success:false,message:"Không tìm thấy hồ sơ khách hàng"});if(!orderId||!productId||stars<1||stars>5||text.length>1000)return res.status(400).json({success:false,message:"Chọn đơn/sản phẩm hợp lệ, 1–5 sao và nội dung tối đa 1.000 ký tự"});const pool=await getPool();tx=new sql.Transaction(pool);await tx.begin(sql.ISOLATION_LEVEL.SERIALIZABLE);const line=(await new sql.Request(tx).input("cid",sql.Int,cid).input("orderId",sql.Int,orderId).input("productId",sql.Int,productId).query(`SELECT TOP 1 ct.MaSanPham FROM HoaDon hd JOIN ChiTietHoaDon ct ON ct.MaHoaDon=hd.MaHoaDon WHERE hd.MaHoaDon=@orderId AND hd.MaKhachHang=@cid AND hd.TrangThai=N'HOAN_THANH' AND hd.TrangThaiThanhToan=N'DA_THANH_TOAN' AND ct.MaSanPham=@productId`)).recordset[0];if(!line)throw new ReviewError(403,"Chỉ đánh giá sản phẩm trong đơn đã hoàn tất và thanh toán của bạn");const created=(await new sql.Request(tx).input("cid",sql.Int,cid).input("orderId",sql.Int,orderId).input("productId",sql.Int,productId).input("stars",sql.TinyInt,stars).input("text",sql.NVarChar(1000),text||null).query("INSERT DanhGiaSanPham(MaHoaDon,MaSanPham,MaKhachHang,SoSao,NoiDung) OUTPUT INSERTED.Id VALUES(@orderId,@productId,@cid,@stars,@text)")).recordset[0];await tx.commit();tx=undefined;res.status(201).json({success:true,data:{Id:created.Id,TrangThai:"CHO_DUYET",message:"Đánh giá đã gửi và đang chờ cửa hàng duyệt"}})}catch(e:any){if(tx)try{await tx.rollback()}catch{}if(e?.number===2601||e?.number===2627)return res.status(409).json({success:false,message:"Bạn đã đánh giá sản phẩm này trong đơn hàng"});fail(res,e)}});
router.post("/:id/anh",customer,async(req:AuthRequest,res)=>{upload(req,res,async(error:any)=>{if(error)return fail(res,new ReviewError(400,"Tối đa 5 ảnh, mỗi ảnh không quá 5 MB"));try{const id=int(req.params.id),cid=await customerId(req),review=await queryOne<any>("SELECT Id FROM DanhGiaSanPham WHERE Id=@id AND MaKhachHang=@cid",{id,cid});if(!review)return res.status(404).json({success:false,message:"Không tìm thấy đánh giá của bạn"});const files=(req.files as Express.Multer.File[]||[]);if(!files.length)return res.status(400).json({success:false,message:"Chọn ít nhất một ảnh"});const exists=Number((await queryOne<any>("SELECT COUNT(*) n FROM AnhDanhGiaSanPham WHERE DanhGiaId=@id",{id}))?.n||0);if(exists+files.length>5)return res.status(409).json({success:false,message:"Mỗi đánh giá được đính kèm tối đa 5 ảnh"});const dir=path.resolve(__dirname,"../../uploads/reviews");await fs.mkdir(dir,{recursive:true});const result=[];for(const f of files){let ext="";if(f.buffer.subarray(0,3).equals(Buffer.from([0xff,0xd8,0xff])))ext=".jpg";else if(f.buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))ext=".png";else if(f.buffer.subarray(0,4).toString()==="RIFF"&&f.buffer.subarray(8,12).toString()==="WEBP")ext=".webp";else throw new ReviewError(400,"Chỉ nhận ảnh JPEG, PNG hoặc WEBP");const name=`review-${id}-${crypto.randomUUID()}${ext}`,url=`/uploads/reviews/${name}`;await fs.writeFile(path.join(dir,name),f.buffer,{flag:"wx"});await query("INSERT AnhDanhGiaSanPham(DanhGiaId,Url) VALUES(@id,@url)",{id,url});result.push({url})}res.status(201).json({success:true,data:result})}catch(e){fail(res,e)}})});
router.get("/",admin,async(req,res)=>{try{const page=Math.max(1,int(req.query.page)||1),limit=Math.min(100,Math.max(1,int(req.query.limit)||20)),status=String(req.query.status||"");const total=Number((await queryOne<any>("SELECT COUNT(*) total FROM DanhGiaSanPham WHERE (@status=N'' OR TrangThai=@status)",{status}))?.total||0);const data=await query<any>(`SELECT d.Id,d.MaHoaDon,d.MaSanPham,d.SoSao,d.NoiDung,d.TrangThai,d.NgayTao,kh.HoTen TenKhachHang,COALESCE(ct.TenSanPhamSnapshot,sp.TenSanPham) TenSanPham FROM DanhGiaSanPham d JOIN KhachHang kh ON kh.MaKhachHang=d.MaKhachHang JOIN SanPham sp ON sp.MaSanPham=d.MaSanPham JOIN ChiTietHoaDon ct ON ct.MaHoaDon=d.MaHoaDon AND ct.MaSanPham=d.MaSanPham WHERE (@status=N'' OR d.TrangThai=@status) ORDER BY d.NgayTao DESC OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY`,{status,offset:(page-1)*limit,limit});res.json({success:true,data,pagination:{page,limit,total,totalPages:Math.max(1,Math.ceil(total/limit))}})}catch(e){fail(res,e)}});
router.patch("/:id/trang-thai",admin,async(req,res)=>{try{const id=int(req.params.id),status=String(req.body.TrangThai||"");if(!["HIEN_THI","AN"].includes(status))return res.status(400).json({success:false,message:"Trạng thái chỉ được HIEN_THI hoặc AN"});const r=await execute("UPDATE DanhGiaSanPham SET TrangThai=@status,UpdatedAt=SYSDATETIME() WHERE Id=@id",{id,status});if(!r.rowsAffected)return res.status(404).json({success:false,message:"Không tìm thấy đánh giá"});res.json({success:true})}catch(e){fail(res,e)}});
export default router;
