import { Ionicons } from "@expo/vector-icons";
import { Image, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { duongDanAnh } from "@/dich_vu/duongDanAnh";
import type { SanPham } from "@/kieu_du_lieu/SanPham";
import { useNewStatus } from "./useNewStatus";

const money = (value: number) => `${Number(value).toLocaleString("vi-VN")}đ`;
export function HomeProductCard({ product, onPress, isFavorite, onToggleFavorite, onAddCart, onBuyNow }: { product: SanPham; onPress: () => void; isFavorite?: boolean; onToggleFavorite?: () => void; onAddCart?: () => void; onBuyNow?: () => void }) {
  const candidateSale = Number(product.GiaKhuyenMaiHienTai ?? product.GiaKhuyenMai ?? 0);
  const sale = product.DangKhuyenMai && candidateSale > 0 && candidateSale < Number(product.GiaBan) ? candidateSale : undefined;
  const percent = sale ? Number(product.PhanTramGiam ?? Math.floor((1 - sale / Number(product.GiaBan)) * 100)) : 0;
  const uri = duongDanAnh(product.HinhAnh);
  const inStock = Number(product.SoLuong) > 0;
  const showNew = useNewStatus(product.isNew, product.newUntil);
  return <View style={styles.card}><TouchableOpacity onPress={onPress} activeOpacity={0.88}><View style={styles.imageWrap}>{uri ? <Image source={{ uri }} style={styles.image} /> : <View style={styles.placeholder}><Ionicons name="image-outline" size={32} color="#98BBA2" /></View>}{showNew&&<Text style={styles.newBadge}>MỚI</Text>}<TouchableOpacity accessibilityLabel="Yêu thích" onPress={onToggleFavorite} style={styles.heart}><Ionicons name={isFavorite ? "heart" : "heart-outline"} size={21} color={isFavorite?"#08785B":"#475569"} /></TouchableOpacity>{percent > 0 && <Text style={styles.badge}>-{percent}%</Text>}</View><Text numberOfLines={2} style={styles.name}>{product.TenSanPham}</Text>{product.TenKhuyenMai&&<Text numberOfLines={1} style={styles.promo}>{product.TenKhuyenMai}</Text>}<Text style={styles.rating}>★ {Number(product.DiemTrungBinh||0).toFixed(1)} <Text style={styles.ratingCount}>({Number(product.SoDanhGia||0)})</Text></Text><View style={styles.priceRow}><View><Text style={styles.price}>{money(sale ?? product.GiaBan)}</Text>{sale && <Text style={styles.oldPrice}>{money(product.GiaBan)}</Text>}{!inStock&&<Text style={styles.out}>Hết hàng</Text>}</View></View></TouchableOpacity><View style={styles.actions}><TouchableOpacity accessibilityLabel={inStock?"Thêm vào giỏ":"Hết hàng"} disabled={!inStock} style={[styles.cart,!inStock&&styles.cartDisabled]} onPress={onAddCart}><Ionicons name="cart-outline" size={17} color={inStock?"#fff":"#82908A"}/><Text style={[styles.actionText,styles.cartActionText,!inStock&&styles.actionDisabled]}>Thêm giỏ</Text></TouchableOpacity><TouchableOpacity disabled={!inStock} style={[styles.buy,!inStock&&styles.cartDisabled]} onPress={onBuyNow}><Text style={[styles.actionText,!inStock&&styles.actionDisabled]}>Mua ngay</Text></TouchableOpacity></View></View>;
}
const styles = StyleSheet.create({ card: { width: "100%", marginRight: 0, backgroundColor:"#fff", borderRadius:15, padding:8, borderWidth:1, borderColor:"#E8EFEA" }, imageWrap: { height: 158, borderRadius: 13, overflow: "hidden", backgroundColor: "#EEF6F0" }, image: { width: "100%", height: "100%", resizeMode: "cover" }, placeholder: { flex: 1, alignItems: "center", justifyContent: "center" }, heart: { position: "absolute", right: 8, top: 8, width: 31, height: 31, borderRadius: 16, backgroundColor: "rgba(255,255,255,.9)", alignItems: "center", justifyContent: "center" }, badge: { position: "absolute", bottom: 8, left: 8, color: "#FFF", backgroundColor: "#E56D3C", borderRadius: 12, paddingHorizontal: 8, paddingVertical: 4, fontWeight: "700", fontSize: 12 },newBadge:{position:"absolute",top:8,left:8,color:"#fff",backgroundColor:"#08785B",borderRadius:10,paddingHorizontal:8,paddingVertical:4,fontWeight:"900",fontSize:10}, name: { fontSize: 13, lineHeight: 18, fontWeight: "700", marginTop: 8, color: "#19372B", minHeight:36 }, promo:{fontSize:11,color:"#08785B",marginTop:2},rating:{fontSize:11,color:"#E99A16",marginTop:3,fontWeight:"800"},ratingCount:{color:"#718096",fontWeight:"400"},out:{fontSize:10,color:"#B42318",fontWeight:"700",marginTop:3}, priceRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" }, price: { color: "#08785B", fontSize: 15, fontWeight: "900", marginTop: 5 }, oldPrice: { color: "#999", fontSize: 11, textDecorationLine: "line-through", marginTop: 2 }, actions:{flexDirection:"row",gap:6,marginTop:8},cart:{height:34,flex:1,borderRadius:10,backgroundColor:"#08785B",alignItems:"center",justifyContent:"center",flexDirection:"row",gap:4},buy:{height:34,flex:1,borderRadius:10,borderWidth:1,borderColor:"#08785B",alignItems:"center",justifyContent:"center"},actionText:{fontSize:10,fontWeight:"800",color:"#08785B"},cartActionText:{color:"#fff"},actionDisabled:{color:"#82908A"},cartDisabled:{backgroundColor:"#EEF1EF",borderColor:"#EEF1EF"} });
