import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect } from "expo-router";
import React, { useCallback, useState } from "react";
import { ActivityIndicator, Alert, Image, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import * as ImagePicker from "expo-image-picker";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAuth } from "@/nguon/AuthContext";
import { khachHangService } from "@/dich_vu/khachHang";
import { KhachHang } from "@/kieu_du_lieu/KhachHang";
import { duongDanAnh } from "@/dich_vu/duongDanAnh";

export default function HoSoCaNhanScreen() {
  const { token, capNhatKhachHang } = useAuth(); const [profile, setProfile] = useState<KhachHang | null>(null);
  const [name, setName] = useState(""); const [birth, setBirth] = useState(""); const [gender, setGender] = useState(""); const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState("");
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [changing, setChanging] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!token) return; setLoading(true); setError(""); try { const r = await khachHangService.layThongTin(token); setProfile(r.data); setName(r.data.HoTen || ""); setBirth((r.data as any).NgaySinh ? String((r.data as any).NgaySinh).slice(0,10) : ""); setGender((r.data as any).GioiTinh || ""); await capNhatKhachHang(r.data); } catch (e: any) { setError(e?.message || "Không thể tải hồ sơ"); } finally { setLoading(false); } }, [token, capNhatKhachHang]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const save = async () => { if (!token || !name.trim()) { setError("Họ tên là bắt buộc."); return; } if (birth && !/^\d{4}-\d{2}-\d{2}$/.test(birth)) { setError("Ngày sinh nhập theo dạng YYYY-MM-DD."); return; } setSaving(true); setError(""); try { const r = await khachHangService.capNhatThongTin({ HoTen:name.trim(), NgaySinh:birth || null, GioiTinh:(gender || null) as any }, token); if (r.data) { setProfile(r.data); await capNhatKhachHang(r.data); } Alert.alert("Đã lưu", "Hồ sơ đã được cập nhật."); } catch(e:any) { setError(e?.message || "Không thể lưu hồ sơ"); } finally { setSaving(false); } };
  const changeAvatar = async () => { if (!token) return; try { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes:["images"], allowsEditing:true, aspect:[1,1], quality:0.85 }); if (result.canceled || !result.assets[0]) return; setSaving(true); const uploaded = await khachHangService.capNhatAnhDaiDien(result.assets[0].uri,token,result.assets[0].mimeType||"image/jpeg"); const updated = profile ? {...profile,AnhDaiDien:uploaded.data.AnhDaiDien} : null; if(updated){setProfile(updated);await capNhatKhachHang(updated)} } catch(e:any){setError(e?.message||"Không thể cập nhật ảnh đại diện")} finally{setSaving(false)} };
  const changePassword = async () => { if (!token) return; if (next.length < 8 || next !== confirm) { setError("Mật khẩu mới cần ít nhất 8 ký tự và phần xác nhận phải khớp."); return; } setChanging(true); setError(""); try { const r = await khachHangService.doiMatKhau(current,next,token); Alert.alert("Đổi mật khẩu",r.message); setCurrent("");setNext("");setConfirm(""); } catch(e:any) { setError(e?.message || "Không thể đổi mật khẩu"); } finally { setChanging(false); } };
  if (loading) return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator color="#176A50"/><Text style={s.muted}>Đang tải hồ sơ…</Text></View></SafeAreaView>;
  return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}><View style={s.header}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="arrow-back" size={23} color="#173E32"/></TouchableOpacity><Text style={s.title}>Hồ sơ cá nhân</Text><View style={{width:23}}/></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    {error ? <View style={s.error}><Text style={s.errorText}>{error}</Text><TouchableOpacity onPress={()=>void load()}><Text style={s.link}>Thử lại</Text></TouchableOpacity></View>:null}
    <TouchableOpacity style={s.avatar} onPress={()=>void changeAvatar()} disabled={saving}>{profile?.AnhDaiDien?<Image source={{uri:duongDanAnh(profile.AnhDaiDien)}} style={s.avatarImage}/>:<Text style={s.initial}>{name.split(/\s+/).slice(-2).map(x=>x[0]).join("").toUpperCase()||"KH"}</Text>}<View style={s.camera}><Ionicons name="camera" size={17} color="white"/></View></TouchableOpacity><TouchableOpacity onPress={()=>void changeAvatar()}><Text style={s.avatarHint}>Đổi ảnh đại diện</Text></TouchableOpacity>
    <View style={s.card}><Text style={s.section}>Thông tin cá nhân</Text><Text style={s.label}>Họ và tên</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="Họ và tên"/><Text style={s.label}>Số điện thoại</Text><TextInput style={[s.input,s.disabled]} value={profile?.SoDienThoai||""} editable={false}/><Text style={s.hint}>Số điện thoại dùng để đăng nhập; muốn đổi cần xác minh.</Text><Text style={s.label}>Email</Text><TextInput style={[s.input,s.disabled]} value={profile?.Email||""} editable={false}/><Text style={s.hint}>Email đăng nhập chỉ đổi sau khi có quy trình xác minh.</Text><Text style={s.label}>Ngày sinh (không bắt buộc)</Text><TextInput style={s.input} value={birth} onChangeText={setBirth} placeholder="YYYY-MM-DD"/><Text style={s.label}>Giới tính</Text><View style={s.gender}>{["Nam","Nữ","Khác"].map(x=><TouchableOpacity key={x} style={[s.choice,gender===x&&s.choiceOn]} onPress={()=>setGender(gender===x?"":x)}><Text style={[s.choiceText,gender===x&&s.choiceTextOn]}>{x}</Text></TouchableOpacity>)}</View><TouchableOpacity style={s.primary} disabled={saving} onPress={()=>void save()}><Text style={s.primaryText}>{saving?"Đang lưu…":"Lưu thay đổi"}</Text></TouchableOpacity></View>
    <View style={s.card}><Text style={s.section}>Bảo mật tài khoản</Text><TextInput style={s.input} value={current} onChangeText={setCurrent} secureTextEntry placeholder="Mật khẩu hiện tại"/><TextInput style={s.input} value={next} onChangeText={setNext} secureTextEntry placeholder="Mật khẩu mới (ít nhất 8 ký tự)"/><TextInput style={s.input} value={confirm} onChangeText={setConfirm} secureTextEntry placeholder="Xác nhận mật khẩu mới"/><TouchableOpacity style={s.outline} disabled={changing} onPress={()=>void changePassword()}><Text style={s.link}>{changing?"Đang đổi…":"Đổi mật khẩu"}</Text></TouchableOpacity></View>
  </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F6FAF7"},header:{height:56,paddingHorizontal:16,backgroundColor:"white",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{fontSize:18,fontWeight:"800",color:"#153D32"},content:{padding:16,paddingBottom:36,gap:14},center:{flex:1,alignItems:"center",justifyContent:"center",gap:12},muted:{color:"#718078"},avatar:{width:92,height:92,borderRadius:46,backgroundColor:"#C7E4D7",alignSelf:"center",alignItems:"center",justifyContent:"center",marginTop:5},avatarImage:{width:92,height:92,borderRadius:46},camera:{position:"absolute",right:0,bottom:0,width:29,height:29,borderRadius:15,backgroundColor:"#176A50",alignItems:"center",justifyContent:"center",borderWidth:2,borderColor:"white"},initial:{fontSize:27,fontWeight:"800",color:"#12503C"},avatarHint:{textAlign:"center",color:"#176A50",marginTop:-7},card:{backgroundColor:"white",padding:16,borderRadius:17,borderWidth:1,borderColor:"#E5EEE8",gap:9},section:{fontSize:17,fontWeight:"800",color:"#173E32",marginBottom:4},label:{fontSize:13,color:"#33433D",marginTop:5},input:{minHeight:48,borderWidth:1,borderColor:"#DDE5E0",borderRadius:11,paddingHorizontal:13,color:"#20332A",backgroundColor:"white"},disabled:{backgroundColor:"#F1F3F2",color:"#7A8580"},hint:{fontSize:12,color:"#75827C",marginTop:-4},gender:{flexDirection:"row",gap:8},choice:{borderWidth:1,borderColor:"#DDE5E0",paddingVertical:10,paddingHorizontal:18,borderRadius:10},choiceOn:{backgroundColor:"#E3F3EB",borderColor:"#176A50"},choiceText:{color:"#33433D"},choiceTextOn:{color:"#176A50",fontWeight:"700"},primary:{backgroundColor:"#176A50",height:50,borderRadius:12,alignItems:"center",justifyContent:"center",marginTop:7},primaryText:{color:"white",fontWeight:"800",fontSize:16},outline:{borderWidth:1,borderColor:"#176A50",height:46,borderRadius:11,alignItems:"center",justifyContent:"center"},link:{color:"#176A50",fontWeight:"700"},error:{backgroundColor:"#FFF0EF",padding:12,borderRadius:11},errorText:{color:"#A23A34"}});
